<a href="https://colab.research.google.com/github/seldoncode/Python_CoderDojo/blob/main/Python_CoderDojo13.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Listas anidadas
* Son listas de listas
* Dentro de una lista los elementos son a su vez otras listas.
* También se llaman matrices o arrays de dos dimensiones o listas bidimiensionales.
* Si las listas anidadas son de nivel 3 se llaman listas tridimencionales, y si son de múltiples dimensiones se llaman multidimiensionales.

In [ ]:
nombres = ["Ana", "Luis", "Eva", "Jose"]
edades = [15,16,14,17]

# organizando la información en forma de matriz
amigos = [["Ana",15],
          ["Luis",16],
          ["Eva",14],
          ["Jose",17]]
amigos

[['Ana', 15], ['Luis', 16], ['Eva', 14], ['Jose', 17]]

In [ ]:
# accediendo al primer elemento de la lista amigos
amigos[0]

['Ana', 15]

In [ ]:
# accediendo a los años de Eva
amigos[2][1]

14

In [ ]:
# ha sido el cumpleaños de Jose
amigos[3][1] += 1
amigos

[['Ana', 15], ['Luis', 16], ['Eva', 14], ['Jose', 18]]

In [ ]:
# se incorpora un nuevo amigo al grupo
amigos.append(["Isa"])    # de momento no hemos puesto la edad
amigos

[['Ana', 15], ['Luis', 16], ['Eva', 14], ['Jose', 18], ['Isa']]

In [ ]:
# añadimos la edad de Isa
amigos[4].append(17)
amigos

[['Ana', 15], ['Luis', 16], ['Eva', 14], ['Jose', 18], ['Isa', 17]]

### Recorriendo listas con un ```for```

In [ ]:
for amigo in amigos:
  print(f"{amigo[0]:5}: {amigo[1]:2}")

Ana  : 15
Luis : 16
Eva  : 14
Jose : 18
Isa  : 17


### Inventarios de videojuegos
* Una tienda de videojuego quiere hacer inventario.
* Clasifica los videojuegos en cuatro tipos:
 - Acción
 - Arcade
 - Estrategia
 - Simulación
* Conocen cuántos videojuegos de cada tipo existen en su tienda.
 - Acción: 456
 - Arcade: 321
 - Estrategia: 209
 - Simulación: 105

In [ ]:
juegos = [["Acción", 456],
          ["Arcade", 321],
          ["Estrategia", 209],
          ["Simulación", 105]]

#### Además quieren añadir su ubicación
Anotando para cada tipo de juego la localización en una estantería indicando fila y columna de la estantería.
* Los juegos de Acción están en la fila=1, columna=3.
* Los juegos de Arcade están en la fila=2, columna=1.
* Los juegos de Estrategia están en la fila=2, columna=2.
* Los juegos de Simulación están en la fila=3, columna=4.

In [1]:
juegos = [["Acción", 456, [1,3]],
          ["Arcade", 321, [2,1]],
          ["Estrategia", 209, [2,2]],
          ["Simulación", 105, [3,4]]]

Se ha vendido un juego de Acción.

In [3]:
juegos[0][1] = 455
juegos

[['Acción', 455, [1, 3]],
 ['Arcade', 321, [2, 1]],
 ['Estrategia', 209, [2, 2]],
 ['Simulación', 105, [3, 4]]]

Imprimiendo los valores con un ```for```.

In [5]:
for j in juegos:
  print(f"{j[0]:10} → {j[1]:2} → {j[2]}")

Acción     → 455 → [1, 3]
Arcade     → 321 → [2, 1]
Estrategia → 209 → [2, 2]
Simulación → 105 → [3, 4]


Deseamos cambiar los juegos de Acción a la fila 3, columna 1.

In [6]:
juegos[0][2] = [3, 1]
juegos

[['Acción', 455, [3, 1]],
 ['Arcade', 321, [2, 1]],
 ['Estrategia', 209, [2, 2]],
 ['Simulación', 105, [3, 4]]]

Ahora queremos cambiar los juegos de Simulación de la posición [3,4] a la posición [2,4].
* Esto es, la columna no cambia, solo cambia la fila.

In [7]:
juegos[3][2][0] = 2
juegos

[['Acción', 455, [3, 1]],
 ['Arcade', 321, [2, 1]],
 ['Estrategia', 209, [2, 2]],
 ['Simulación', 105, [2, 4]]]

#### Cambiar el formato de impresión de la tabla
Deseamos que se imprima según este formato:
* Acción &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- &nbsp;Cantidad: 455 → Columna: 1, Fila: 3.
* Arcade &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- &nbsp;Cantidad: 321 → Columna: 1, Fila: 2.
* Estrategia &nbsp;&nbsp;- &nbsp;Cantidad: 209 → Columna: 2, Fila: 2.
* Simulación - &nbsp;Cantidad: 105 → Columna: 4, Fila: 2.

In [8]:
for j in juegos:
  print(f"{j[0]:10} - Cantidad: {j[1]:2} → Columna: {j[2][1]}, Fila: {j[2][0]}.")

Acción     - Cantidad: 455 → Columna: 1, Fila: 3.
Arcade     - Cantidad: 321 → Columna: 1, Fila: 2.
Estrategia - Cantidad: 209 → Columna: 2, Fila: 2.
Simulación - Cantidad: 105 → Columna: 4, Fila: 2.


### Inventarios de letras en dos cajones
* En una ferretería guardan letras de madera en dos cajones.
* Imprimir el contenido de los dos cajones, indicando el número de letras de cada tipo y en orden alfabético.
* Cada cajón tiene 3 filas y 4 columnas
* Cajón 1
  - Fila 1: A,B,C,D,E
  - Fila 2: F,G,H,I,J
  - Fila 3: K,L,M,N,Ñ
* Cajón 1:
 - A: 21 letras
 - B: 16 letras
 - C: 15 letras
 - D: 12 letras
 - E: 31 letras
 - F: 10 letras
 - G: 11 letras
 - H: 9 letras
 - I: 22 letras
 - J: 14 letras
 - K: 8 letras
 - L: 20 letras
 - M: 19 letras
 - N: 18 letras
 - Ñ: 7 letras
* Cajón 2
  - Fila 1: O,P,Q,R,S
  - Fila 2: T,U,V,W,X
  - Fila 3: Y,Z, , , 
   + Los tres últimos elementos de la fila 3 están vacíos
* Cajón 2:
 - O: 24 letras
 - P: 17 letras
 - Q: 13 letras
 - R: 19 letras
 - S: 21 letras
 - T: 25 letras
 - U: 32 letras
 - V: 15 letras
 - W: 6 letras
 - X: 7 letras
 - Y: 12 letras
 - Z: 10 letras

In [12]:
fila11 = [["A",21],
          ["B",16],
          ["C",15],
          ["D",12],
          ["E",31]]

fila12 = [["F",10],
          ["G",11],
          ["H",9],
          ["I",22],
          ["J",14]]

fila13 = [["K",8],
          ["L",20],
          ["M",19],
          ["N",18],
          ["Ñ",7]]

cajon1 = [fila11, fila12, fila13]


fila21 = [["O",24],
          ["P",17],
          ["Q",13],
          ["R",19],
          ["S",21]]

fila22 = [["T",25],
          ["U",32],
          ["V",15],
          ["W",6],
          ["X",7]]

fila23 = [["Y",12],
          ["Z",10],
          ["",0],
          ["",0],
          ["",0]]

cajon2 = [fila21, fila22, fila23]

cajonera = [cajon1, cajon2]
cajonera

[[[['A', 21], ['B', 16], ['C', 15], ['D', 12], ['E', 31]],
  [['F', 10], ['G', 11], ['H', 9], ['I', 22], ['J', 14]],
  [['K', 8], ['L', 20], ['M', 19], ['N', 18], ['Ñ', 7]]],
 [[['O', 24], ['P', 17], ['Q', 13], ['R', 19], ['S', 21]],
  [['T', 25], ['U', 32], ['V', 15], ['W', 6], ['X', 7]],
  [['Y', 12], ['Z', 10], ['', 0], ['', 0], ['', 0]]]]

#### Imprimir el inventario de la cajonera

In [15]:
print("CAJONERA".center(50))
print()
for cajon in cajonera:
  for fila in cajon:
    for celda in fila:
      print(f"{celda[0]:1} : {celda[1]:2}     ", end="")
    print()
  print()

                     CAJONERA                     

A : 21     B : 16     C : 15     D : 12     E : 31     
F : 10     G : 11     H :  9     I : 22     J : 14     
K :  8     L : 20     M : 19     N : 18     Ñ :  7     

O : 24     P : 17     Q : 13     R : 19     S : 21     
T : 25     U : 32     V : 15     W :  6     X :  7     
Y : 12     Z : 10       :  0       :  0       :  0     



#### Crear un menú
* Para disminuir unidades cuando se vende alguna letra
* Para añadir unidades cuando llega un pedido

In [22]:
while True:
  print("1. Mostrar inventario")
  print("2. Venta de letra")
  print("3. Reposición de letra")
  print("4. Salir")
  
  opcion = input("→ ")

  if opcion == "1":
    print()
    print("CAJONERA".center(50))
    print()
    for cajon in cajonera:
      for fila in cajon:
        for celda in fila:
          print(f"{celda[0]:1} : {celda[1]:2}     ", end="")
        print()
      print()
  elif opcion == "2":
    letra = input("Indique la letra vendida: ").upper()
    for cajon in cajonera:
      for fila in cajon:
        for celda in fila:
          if letra == celda[0]:
            unidades_vendidas = int(input("Indique el número de unidades vendidas (si 1 presione ENTER): ") or 1)
            if celda[1] >= unidades_vendidas:
              print(f"Entregando {unidades_vendidas} unidades de la letra {celda[0]}.")
              celda[1] -= unidades_vendidas
            else: 
              print(f"Stock insuficiente, solo podemos venderle {celda[1]} unidades.")
  elif opcion == "3":
    letra = input("Indique la letra a reponer: ").upper()
    for cajon in cajonera:
      for fila in cajon:
        for celda in fila:
          if letra == celda[0]:
            unidades_repuestas = int(input("Indique el número de unidades repuestas: "))
            print(f"Reponiendo {unidades_repuestas} unidades de la letra {celda[0]}.")
            celda[1] += unidades_repuestas
  elif opcion == "4":
    print("Fin del programa")
    break
  else:
    print("Por favor, introduzca una opción correcta.")

1. Mostrar inventario
2. Venta de letra
3. Reposición de letra
4. Salir
→ 3
Indique la letra a reponer: z
Indique el número de unidades repuestas: 9
Reponiendo 9 unidades de la letra Z.
1. Mostrar inventario
2. Venta de letra
3. Reposición de letra
4. Salir
→ 1

                     CAJONERA                     

A : 21     B : 16     C : 15     D : 12     E : 31     
F : 10     G : 11     H :  9     I : 22     J : 14     
K :  8     L : 20     M : 19     N : 18     Ñ :  7     

O : 24     P : 17     Q : 13     R : 19     S : 21     
T : 25     U : 32     V : 15     W :  6     X :  7     
Y : 12     Z : 19       :  0       :  0       :  0     

1. Mostrar inventario
2. Venta de letra
3. Reposición de letra
4. Salir
→ 4
Fin del programa


### Transformar un lista bidimensional en dos unidimensionales
* Nos dan la lista bidimiensional siguiente:
 - grupos = [[1,"A"],[2,"B"],[3,"C"],[4,"D"],[5,"E"],[6,"F"],[7,"G"],[8,"H"],[9,"I"],[0,"J"]]
* Deseamos crear un algoritmo que transforme la lista bidimiesional anterior en las dos listas unidimensionales siguientes.
 - numeros = [1,2,3,4,5,6,7,8,9,0]
 - letras = ["A","B","C","D","E","F","G","H","I","J"]

In [25]:
grupos = [[1,"A"],[2,"B"],[3,"C"],[4,"D"],[5,"E"],[6,"F"],[7,"G"],[8,"H"],[9,"I"],[0,"J"]]
print(grupos)
numeros = []
letras = []
for grupo in grupos:
  numeros.append(grupo[0])
  letras.append(grupo[1])

print(numeros)
print(letras)

[[1, 'A'], [2, 'B'], [3, 'C'], [4, 'D'], [5, 'E'], [6, 'F'], [7, 'G'], [8, 'H'], [9, 'I'], [0, 'J']]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 0]
['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']


### Transformar dos listas unidimensionales en una lista bidimensional
* Nos dan las listas unidimiensionales siguientes:
 - numeros = [1,2,3,4,5,6,7,8,9,0]
 - letras = ["A","B","C","D","E","F","G","H","I","J"]
 - estamos suponiendo que el número de elementos de ambas listas son iguales
* Deseamos crear un algoritmo que transforme esas listas unidimiesionales en una lista bidimensional como esta:
 - grupos = [[1,"A"],[2,"B"],[3,"C"],[4,"D"],[5,"E"],[6,"F"],[7,"G"],[8,"H"],[9,"I"],[0,"J"]]

#### Solución 1 con ```append```

In [ ]:
numeros = [1,2,3,4,5,6,7,8,9,0]
letras = ["A","B","C","D","E","F","G","H","I","J"]
n = len(numeros)
grupos = []
for i in range(n):
  grupos.append([numero[i],letras[i]])

#### Solución 2 inicializando una lista bidimensional
* Inicializamos una lista bidimiensional donde los números son todos cero y las letras están vacías.
* grupos = [[0, ''], [0, ''], [0, ''], [0, ''], [0, ''], [0, ''], [0, ''], [0, ''], [0, ''], [0, '']]
* No intentes inicializar la lista así:
 - grupos = [[0,'']]*n
 - aparentemente el resultado será el mismo pero esta forma de inicializar la lista grupos, lo que hace es repetir el primer elemento [0,''] n veces, pero se trata del mismo elemento
 - Recordemos que para copiar bien una lista se ha de hacer una copia profunda, si se pone el signo de multiplicar * lo que se está haciendo es una copia del mismo elemento de la lista 10 veces, de forma que al cambiar uno se cambian todos porque son en realidad el mismo.

In [3]:
numeros = [1,2,3,4,5,6,7,8,9,0]
letras = ["A","B","C","D","E","F","G","H","I","J"]
n = len(numeros)
grupos = [[0,''] for j in range(n)]  # forma correcta de inicializar una lista con n elementos diferentes
print(grupos)

for i in range(n):
  grupos[i][0] = numeros[i]         # con este sistema no es necesario usar append
  grupos[i][1] = letras[i]          # ya que lo que hacemos es cambiar el valor de los elementos ya existentes
print(grupos)

[[0, ''], [0, ''], [0, ''], [0, ''], [0, ''], [0, ''], [0, ''], [0, ''], [0, ''], [0, '']]
[[1, 'A'], [2, 'B'], [3, 'C'], [4, 'D'], [5, 'E'], [6, 'F'], [7, 'G'], [8, 'H'], [9, 'I'], [0, 'J']]


# Copia de listas
Recordemos primero cómo se hace una copia de una lista que no sea una copia independiente.

In [4]:
l1 = [1,2,3]
l2 = l1         # esto no es una copia independiente, l1 y l2 son la misma lista
print(id(l1))   # ambas listas tienen el mismo id
print(id(l2))   # ambas ocupan el mismo lugar en memoria ya que en realidad son la misma lista

140555754385312
140555754385312


In [5]:
# si cambiarmos un elemento de la lista l1 se cambia también en l2
l1[0] = 7
l2

[7, 2, 3]

## Haciendo correctamente una copia independiente de una lista
### Método 1 usando ```lista[:]```

In [6]:
l1 =[1,2,3]
l2 = l1[:]       # así copiamos todos los elementos de la lista, pero l2 es una lista distinta de l1
print(id(l1))    # las listas tienen distinto id
print(id(l2))    # ocupan distinto lugar en memoria ya que en realidad se trata de listas distintas

140555754838208
140555823203664


In [7]:
# si cambiarmos un elemento de la lista l1, la lista l2 no se altera
l1[0] = 7
l2

[1, 2, 3]

### Método 2 usando ```list```

In [8]:
l1 = [1,2,3]
l2 = list(l1)
print(id(l1))    # las listas tienen distinto id
print(id(l2))

140555755003088
140555754740864


In [9]:
# si cambiarmos un elemento de la lista l1, la lista l2 no se altera
l1[0] = 7
l2

[1, 2, 3]

## El problema surge con las listas anidadas

In [10]:
p = [1, [2,3], [4,5,6]]
q = list(p)
print(p)
print(q)
p[0] = 10            # en este caso funciona bien, al cambiar el elemento p[0] no cambia q[0]
p[1][0] = 20         # funciona mal, ya que al cambiar p[1][0] también cambia q[1][0] 
p[2][0] = 40         # funciona mal, ya que al cambiar p[2][0] también cambia q[2][0]
print()
print(p)
print(q)

[1, [2, 3], [4, 5, 6]]
[1, [2, 3], [4, 5, 6]]

[10, [20, 3], [40, 5, 6]]
[1, [20, 3], [40, 5, 6]]


#### Solución 1 copia profunda manual

In [3]:
p = [1, [2,3], [4,5,6]]
q = [p[0],list(p[1]),list(p[2])]
print(p)
print(q)
p[0] = 10            # cambiamos el valor de p[0] y no cambia q[0]
p[1][0] = 20         # cambiamos p[1][0] y no cambia q[1][0] 
p[2][0] = 40         # cambiamos p[2][0] y no cambia q[2][0]
print()
print(p)
print(q)

[1, [2, 3], [4, 5, 6]]
[1, [2, 3], [4, 5, 6]]

[10, [20, 3], [40, 5, 6]]
[1, [2, 3], [4, 5, 6]]


#### Solución 2 concatenando listas


In [17]:
p = [1, [2,3], [4,5,6]]
q = [p[0]] + [list(p[1])] + [list(p[2])]
print(p)
print(q)
p[0] = 10            # cambiamos el valor de p[0] y no cambia q[0]
p[1][0] = 20         # cambiamos p[1][0] y no cambia q[1][0] 
p[2][0] = 40         # cambiamos p[2][0] y no cambia q[2][0]
print()
print(p)
print(q)

[1, [2, 3], [4, 5, 6]]
[1, [2, 3], [4, 5, 6]]

[10, [20, 3], [40, 5, 6]]
[1, [2, 3], [4, 5, 6]]


#### Solución 3 con segmentos de indexación

In [19]:
p = [1, [2,3], [4,5,6]]
q = [p[0], p[1][:], p[2][:]]
print(p)
print(q)
p[0] = 10            # cambiamos el valor de p[0] y no cambia q[0]
p[1][0] = 20         # cambiamos p[1][0] y no cambia q[1][0] 
p[2][0] = 40         # cambiamos p[2][0] y no cambia q[2][0]
print()
print(p)
print(q)

[1, [2, 3], [4, 5, 6]]
[1, [2, 3], [4, 5, 6]]

[10, [20, 3], [40, 5, 6]]
[1, [2, 3], [4, 5, 6]]


#### Solución 4 sin librería

In [14]:
p = [1, [2,3], [4,5,6]]
q = []
for i in range(len(p)):
  if type(p[i])==list:
    q.append(list(p[i]))
  else:
    q.append(p[i])
print(p)
print(q)
p[0] = 10            # cambiamos el valor de p[0] y no cambia q[0]
p[1][0] = 20         # cambiamos p[1][0] y no cambia q[1][0] 
p[2][0] = 40         # cambiamos p[2][0] y no cambia q[2][0]
print()
print(p)
print(q)

[1, [2, 3], [4, 5, 6]]
[1, [2, 3], [4, 5, 6]]

[10, [20, 3], [40, 5, 6]]
[1, [2, 3], [4, 5, 6]]


#### Solución 5 copia profunda usando la librería ```Deepcopy```

In [16]:
import copy
p = [1, [2,3], [4,5,6]]
q = copy.deepcopy(p) # con deepcopy conseguimos que la copia de listas de listas sea una copia independiente           
print(p)
print(q)
p[0] = 10            # cambiamos el valor de p[0] y no cambia q[0]
p[1][0] = 20         # cambiamos p[1][0] y no cambia q[1][0] 
p[2][0] = 40         # cambiamos p[2][0] y no cambia q[2][0]
print()
print(p)
print(q)

[1, [2, 3], [4, 5, 6]]
[1, [2, 3], [4, 5, 6]]

[10, [20, 3], [40, 5, 6]]
[1, [2, 3], [4, 5, 6]]


## Aplanar una lista
Se denomina aplanar una lista a tomar una lista anidada y con todos sus elementos obtener una lista unidimensional.

In [20]:
datos = [[1,2,3], [4,5,6], [7,8,9]]
plana = []

for lista in datos:
  for elemento in lista:
    plana.append(elemento)

plana

[1, 2, 3, 4, 5, 6, 7, 8, 9]

### Función ```type```

In [22]:
type(5)

int

In [23]:
type(5) == int

True

In [24]:
type([1,2,3])

list

### Función ```isinstance```

In [26]:
isinstance(5, int)

True

In [27]:
isinstance([1,2,3], list)

True

### Aplanar una lista que contiene tanto listas como números enteros

#### Solución 1 con ```type```

In [21]:
datos = [[1,2,3],4,5,[6,7],8,9]
plana = []

for dato in datos:
  if type(dato) == int:
    plana.append(dato)
  elif type(dato) == list:
    for elemento in dato:
      plana.append(elemento)

plana

[1, 2, 3, 4, 5, 6, 7, 8, 9]

#### Solución 2 con ```isinstance```

In [28]:
datos = [[1,2,3],4,5,[6,7],8,9]
plana = []

for dato in datos:
  if isinstance(dato, int):
    plana.append(dato)
  elif isinstance(dato, list):
    for elemento in dato:
      plana.append(elemento)

plana

[1, 2, 3, 4, 5, 6, 7, 8, 9]

### Aplanar una lista compuesta por números y letras

In [52]:
datos = [[1,2,3,4],
         ['a','b','c','d'],
         [5,6,7,8],
         ['e','f','g','h'],
         [9,10,11,12],
         ['i','j','k','l'],
         [13,14,15,16],
         ['m','n','ñ','o']]
print(datos)

[[1, 2, 3, 4], ['a', 'b', 'c', 'd'], [5, 6, 7, 8], ['e', 'f', 'g', 'h'], [9, 10, 11, 12], ['i', 'j', 'k', 'l'], [13, 14, 15, 16], ['m', 'n', 'ñ', 'o']]


#### Imprimir la lista con formato usando ```in```

In [53]:
for lista in datos:
  for elemento in lista:
    print(f"{elemento:>5}", end="")
  print()

    1    2    3    4
    a    b    c    d
    5    6    7    8
    e    f    g    h
    9   10   11   12
    i    j    k    l
   13   14   15   16
    m    n    ñ    o


#### Imprimir la lista con formato usando ```range``` en el ```for```

In [54]:
for i in range(len(datos)):
  for j in range(len(datos[i])):
    print(f"{datos[i][j]:>5}", end=" ")
  print()

    1     2     3     4 
    a     b     c     d 
    5     6     7     8 
    e     f     g     h 
    9    10    11    12 
    i     j     k     l 
   13    14    15    16 
    m     n     ñ     o 


#### Extraemos la lista numeros

In [42]:
numeros = []
for i in range(0,len(datos),2):
  for j in range(len(datos[i])):
    numeros.append(datos[i][j])
numeros

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]

#### Extraemos la lista letras

In [51]:
letras = []
for i in range(1,len(datos),2):
  for j in range(len(datos[i])):
    letras.append(datos[i][j])
letras

['a',
 'b',
 'c',
 'd',
 'e',
 'f',
 'g',
 'h',
 'i',
 'j',
 'k',
 'l',
 'm',
 'n',
 'ñ',
 'o']

##### Imprimiendo solo las letras

In [57]:
for i in range(len(datos)):
  if i%2:                                # solo letras
    for j in range(len(datos[i])):
      print(datos[i][j], end=" ")
    print()

a b c d 
e f g h 
i j k l 
m n ñ o 
